export const CART_ADD_STARTED = "CART_ADD_STARTED";
export const CART_ADD_SUCCESS = "CART_ADD_SUCCESS";
export const CART_ADD_FAIL = "CART_ADD_FAIL";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
